apiVersion: v1
kind: Pod 
metadata:
  name: nginxnp
  labels: 
    apps: nginxnp
spec: 
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1  
kind: Service
metadata: 
   name: nodeport
   labels: 
     apps: nodeport
spec: 
   selector:
        app: nginxnp
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
   type: NodePort    

